include: package:pedantic/analysis_options.yaml

analyzer:
  exclude:
    - lib/generated/**/*.dart
    - lib/**/*.g.dart
  # strong-mode:
  #   implicit-casts: false
  #   implicit-dynamic: false
  # enable-experiment:
  #   - non-nullable
